FROM arm32v7/debian:stretch

# install required packages
RUN apt-get update && apt-get install -yq --no-install-recommends \
    build-essential \
    wget \
    unzip \
    libtool \
    pkg-config \
    autoconf \
    automake \
    net-tools \
    can-utils \
    make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# define our working directory in the container
WORKDIR usr/src/app

# Move app to filesystem
COPY ./app ./

# Start app
CMD ["bash", "/usr/src/app/start.sh"]
